[project]
name = "analise-biomecanica"
version = "0.1.0"
description = "Projeto de análise biomecânica"
requires-python = ">=3.9,<3.12"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
